; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; This file contains PlatformIO configuration.
;
; File is integral part of MIDI-Controller's software, full source code, and license is avalible on github:
; https://github.com/ANTowski-1/MIDI-Controller-Software/tree/main
;
; Copyright 2026, Antoni Kołaczek
; Licensed under GPL-3.0.

[env:esp32-s3-devkitc1-n4r8]
platform = espressif32
board = esp32-s3-devkitc1-n4r8
framework = arduino
lib_deps = 
	tttapa/Control Surface@^2.1.3
	bitbank2/bb_spi_lcd@^2.9.9
build_flags = 
	-DARDUINO_USB_MODE=0
	-DARDUINO_USB_CDC_ON_BOOT=1
	-D VERSION=1
	-D debugMode=0 ;Turn ON/OFF additinal debug messeges on SERIAL0 output 
	-D COMPILE_UNIX_TIME=$UNIX_TIME
board_build.partitions = partitions.csv
extra_scripts = pre:copyCSPatch.py ;Copy USBMIDI_ESP32.hpp file from CS 3.1.2 into the library folder. 
								   ;Patch allows for the mixer to function even when not connected via USB